### ISSUE TITLE
Skill only responds to "Are you alexa?"

### ISSUE THREAD

**Issue by ghzeni** [k4l1sh/alexa-gpt#7]
Hello!

Thank you so much for creating this, it's such a helpful guide on how to create a gpt skill for Alexa. I've been using it for a while now, but a few weeks ago my skill stopped working. I double-checked everything according to your code and everything seems to be the same, but my skill will only respond to the question "Are you alexa?" and crash if I ask it anything else. 

I am also very clueless on how to properly debug this. I can provide you with some logs once I find out where to find 'em 😄

**Comment by k4l1sh** [comment]
Some recent changes were made to force the OpenAI API version, change to the gpt-3.5-turbo-1106 model, remove the stop and increase the number of tokens in commits 2d012ce d3deb1b 2669d69.

If you can update the code, see if it solves the problem.

This error may be due to the connection with the ChatGPT API, The response of model gpt-3.5-turbo that was being used previously seems a little slow, and they are to make it legacy in Dec 11.

This error could also be due to Alexa's microphone.

If this doesn't solve the problem, you can show the output in the Test tab within the skill, to see if the error appears
